from aiogram.fsm.state import State, StatesGroup


class AdminTicketStates(StatesGroup):
    waiting_reply_text = State()
    waiting_ticket_search = State()
    waiting_user_id = State()
    waiting_balance_amount = State()
    waiting_days_amount = State()
    waiting_transfer_days = State()
    waiting_promo_code = State()
    waiting_promo_target = State()
    waiting_promo_value = State()
    waiting_promo_expires = State()
    waiting_promo_limit = State()
    waiting_promo_edit_value = State()
    waiting_promo_edit_expires = State()
    waiting_promo_edit_limit = State()
    waiting_broadcast_text = State()
    waiting_broadcast_media = State()
    # Server monitoring
    waiting_server_name = State()
    waiting_server_ip = State()
    waiting_server_panel_url = State()
    waiting_server_api_key = State()
    waiting_server_provider = State()
    waiting_server_monthly_cost = State()
    waiting_server_balance = State()
    waiting_server_payment_date = State()
    waiting_server_notes = State()
    waiting_server_edit_balance = State()
    waiting_server_edit_payment_date = State()
    waiting_server_edit_monthly_cost = State()
